import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Plus, X, ExternalLink, Github, Code2, CheckCircle2, Layers } from 'lucide-react';

export const PortfolioSection = () => {
  const [filter, setFilter] = useState('*');
  const [activeLightbox, setActiveLightbox] = useState(null);

  const portfolioItems = [
    {
      id: 'p0',
      title: 'MEESHO WEBSITE CLONE',
      category: 'third',
      categoryLabel: 'React ',
      image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&q=80&w=800',
      projectDescription:
        'Developed a responsive Meesho-inspired e-commerce website focusing on creating a clean, modern, and user-friendly shopping interface. The project was built to enhance front-end development skills using React and to understand component-based application development.',
      technologies: ['React.js', 'HTML', 'CSS', 'JavaScript', 'React Hooks'],
      contributions: [
        'Developed the complete frontend using React.js.',
        'Built a responsive and user-friendly interface inspired by the Meesho website.',
        'Used React Hooks for state management and component functionality.',
        'Created reusable React components to improve code maintainability and scalability.',
        'Designed the application to provide a smooth user experience across different devices.',
      ],
     
    },
    {
      id: 'p1',
      title: 'Farm2Industry Platform',
      category: 'second',
      categoryLabel: ' Web App',
      image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&q=80&w=800',
      projectDescription:
        'Farm2Industry is a web-based platform developed to eliminate intermediaries between farmers and industries by enabling direct communication and transactions. The platform allows farmers to showcase their agricultural products, while industries can browse available products and purchase them directly based on their requirements, ensuring a transparent and efficient supply chain.',
      technologies: ['HTML', 'CSS', 'JavaScript', 'Node.js', 'Express.js', 'MySQL'],
      contributions: [
        'Developed the frontend of the application using HTML, CSS, and JavaScript.',
        'Designed responsive and user-friendly interfaces for both the Farmer Dashboard and Industry Dashboard.',
        'Implemented product listing pages, interactive forms, and client-side validation to improve user experience.',
        'Collaborated with the backend team to integrate frontend components with the application\'s APIs.',
      ],
     
    },
    {
      id: 'p2',
      title: 'Self Powered Speed Measuring System',
      category: 'first',
      categoryLabel: 'IoT & Hardware',
      image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800',
      projectDescription:
        'Developed a self-powered motor speed measuring system that eliminates the need for frequent battery replacement by utilizing the motor\'s rotational energy. The system converts the kinetic energy generated by the rotating motor shaft into electrical energy, which powers the speed measurement circuit. An IR sensor is used to detect the motor\'s rotation, and the calculated RPM is processed by the ESP8266 microcontroller and displayed in real time on an LCD.',
      technologies: ['ESP8266 Microcontroller', 'IR Sensor', 'LCD Display', 'DC Motor', 'Energy Harvesting Generator', 'Embedded C / Arduino IDE'],
      contributions: [
        'Designed and assembled the hardware components of the system.',
        'Integrated the IR sensor with the ESP8266 for accurate RPM measurement.',
        'Developed the microcontroller program to calculate and display motor speed in real time.',
        'Implemented an energy harvesting mechanism that converts the motor\'s rotational (kinetic) energy into electrical power to operate the speed measuring unit.',
        'Tested and validated the system for continuous speed monitoring without relying on external battery power.',
      ],
     
    },
    {
      id: 'p3',
      title: 'Netflix Website Clone',
      category: 'second',
      categoryLabel: 'UI Clone',
      image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&q=80&w=800',
      projectDescription:
        'Developed a responsive Netflix-inspired website by recreating the original platform\'s user interface using modern front-end technologies. The project focused on replicating the overall design, layout, and user experience of Netflix while improving front-end development skills through hands-on implementation.',
      technologies: ['HTML', 'CSS', 'JavaScript'],
      contributions: [
        'Developed the complete frontend using HTML, CSS, and JavaScript.',
        'Recreated the Netflix homepage with a responsive and visually appealing user interface.',
        'Implemented interactive features such as button clicks, navigation effects, and basic UI animations using JavaScript.',
        'Focused on pixel-perfect design, responsive layouts, and an improved user experience across different screen sizes.',
      ],
      
    },
    {
      id: 'p4',
      title: 'Personal Portfolio Website',
      category: 'third',
      categoryLabel: 'React / Tailwind',
      image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=800',
      projectDescription:
        'Developed a modern and responsive personal portfolio website to showcase my projects, technical skills, certifications, and contact information. The website was designed with a clean and interactive user interface, providing a professional platform to highlight my work and achievements.',
      technologies: ['React.js', 'Tailwind CSS', 'Motion', 'Lucide Icons'],
      contributions: [
        'Developed the complete frontend using React.js and Tailwind CSS.',
        'Designed a responsive and visually appealing user interface compatible with desktop and mobile devices.',
        'Created reusable React components for better code organization and maintainability.',
        'Showcased personal projects, technical skills, and contact details in a structured and user-friendly layout.',
      ],
     
    },
  ];

  const filteredItems =
    filter === '*'
      ? portfolioItems
      : portfolioItems.filter((item) => item.category === filter);

  return (
    <section id="portfolio" className="py-20 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header with Background Stroke */}
        <div className="relative flex items-center justify-center mb-12 select-none">
          <h1 className="text-6xl sm:text-8xl md:text-9xl font-black uppercase text-stroke-bg tracking-widest text-center">
            project
          </h1>
          <h2 className="absolute text-2xl sm:text-4xl font-bold uppercase text-[#0BCEAF] tracking-wider">
            My Projects
          </h2>
        </div>

        {/* Filter Navigation */}
        <div className="flex justify-center mb-12">
          <ul className="flex flex-wrap justify-center items-center gap-2 sm:gap-4 bg-gray-100 p-1.5 rounded-full border border-gray-200">
            <li>
              <button
                type="button"
                onClick={() => setFilter('*')}
                className={`px-5 py-2 text-sm font-semibold rounded-full transition-all duration-300 ${
                  filter === '*'
                    ? 'bg-[#0BCEAF] text-white shadow-md'
                    : 'text-gray-600 hover:text-[#0BCEAF]'
                }`}
              >
                All Projects
              </button>
            </li>
            <li>
              <button
                type="button"
                onClick={() => setFilter('second')}
                className={`px-5 py-2 text-sm font-semibold rounded-full transition-all duration-300 ${
                  filter === 'second'
                    ? 'bg-[#0BCEAF] text-white shadow-md'
                    : 'text-gray-600 hover:text-[#0BCEAF]'
                }`}
              >
                Web Apps
              </button>
            </li>
            <li>
              <button
                type="button"
                onClick={() => setFilter('first')}
                className={`px-5 py-2 text-sm font-semibold rounded-full transition-all duration-300 ${
                  filter === 'first'
                    ? 'bg-[#0BCEAF] text-white shadow-md'
                    : 'text-gray-600 hover:text-[#0BCEAF]'
                }`}
              >
                IoT & Hardware
              </button>
            </li>
            <li>
              <button
                type="button"
                onClick={() => setFilter('third')}
                className={`px-5 py-2 text-sm font-semibold rounded-full transition-all duration-300 ${
                  filter === 'third'
                    ? 'bg-[#0BCEAF] text-white shadow-md'
                    : 'text-gray-600 hover:text-[#0BCEAF]'
                }`}
              >
                React UI
              </button>
            </li>
          </ul>
        </div>

        {/* Portfolio Items Grid */}
        <motion.div layout className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <AnimatePresence>
            {filteredItems.map((item) => (
              <motion.div
                key={item.id}
                layout
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                transition={{ duration: 0.3 }}
                className="portfolio-card group relative rounded-2xl overflow-hidden shadow-md hover:shadow-xl border border-gray-100 bg-white flex flex-col transition-all duration-300"
              >
                {/* Image Container with Title Overlay */}
                <div
                  className="relative h-64 overflow-hidden bg-gray-900 cursor-pointer"
                  onClick={() => setActiveLightbox(item)}
                >
                  <img
                    src={item.image}
                    alt={item.title}
                    onError={(e) => {
                      e.currentTarget.onerror = null;
                      e.currentTarget.src =
                        'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=800';
                    }}
                    className="w-full h-full object-cover transform transition-transform duration-700 group-hover:scale-110"
                  />

                  {/* Always-visible Title & Category Gradient Overlay on Image */}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/30 to-transparent flex flex-col justify-between p-5 transition-opacity duration-300 group-hover:opacity-20">
                    <div className="flex justify-between items-start">
                    
                    </div>

                    
                    <div className="transition-all duration-300 group-hover:opacity-0">
                      <h4 className="text-xl font-extrabold text-white drop-shadow-md mb-1">
                        {item.title}
                      </h4>
                      <p className="text-xs text-gray-200 line-clamp-2 opacity-90">
                        {item.projectDescription}
                      </p>
                    </div>
                  </div>

                  {/* Hover Overlay with Action Button */}
                  <div className=" absolute inset-0  bg-gradient-to-t from-black/85 via-black/30 to-transparent ... group-hover:opacity-20 flex flex-col items-center justify-center p-6 text-center text-white opacity-0 group-hover:opacity-100 transition-all duration-300">
                    <span className="text-xs  text-[#0BCEAF]  uppercase font-extrabold tracking-wider bg-black/30 px-3 py-1 rounded-full mb-3 border border-white/20">
                      {item.categoryLabel}
                    </span>
                    <h4 className="text-xl font-bold mb-3 text-white drop-shadow">{item.title}</h4>
                    <div className="flex items-center gap-2 bg-white text-[#0BCEAF] font-bold text-sm px-5 py-2.5 rounded-full shadow-lg transform group-hover:scale-105 transition-transform">
                    
                      <span>View Details</span>
                    </div>
                  </div>
                </div>

                {/* Card Info Footer */}
                
              </motion.div>
            ))}
          </AnimatePresence>
        </motion.div>
      </div>

      {/* Lightbox Modal */}
      {activeLightbox && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm overflow-y-auto"
          onClick={() => setActiveLightbox(null)}
        >
          <div
            className="bg-white rounded-2xl max-w-3xl w-full p-6 sm:p-8 relative shadow-2xl overflow-hidden my-8 max-h-[90vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={() => setActiveLightbox(null)}
              className="absolute top-4 right-4 text-gray-400 hover:text-gray-700 p-2 rounded-full bg-gray-100 hover:bg-gray-200 z-10 transition-colors"
              aria-label="Close dialog"
            >
              <X className="w-6 h-6" />
            </button>

            {/* Banner Image */}
            <div className="rounded-xl overflow-hidden mb-6 max-h-72 shadow-md relative">
              <img
                src={activeLightbox.image}
                alt={activeLightbox.title}
                onError={(e) => {
                  e.currentTarget.onerror = null;
                  e.currentTarget.src =
                    'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=800';
                }}
                className="w-full h-full object-cover"
              />
              <div className="absolute top-4 left-4">
                <span className="text-xs font-extrabold text-white uppercase tracking-wider bg-[#0BCEAF] px-3.5 py-1.5 rounded-full shadow-lg">
                  {activeLightbox.categoryLabel}
                </span>
              </div>
            </div>

            {/* Project Title & Overview */}
            <div>
              <h3 className="text-2xl sm:text-3xl font-black text-gray-900 mb-3">
                {activeLightbox.title}
              </h3>

              <div className="mb-6 bg-gray-50 p-4 rounded-xl border border-gray-100">
                <h4 className="text-xs uppercase font-extrabold tracking-wider text-gray-500 mb-2 flex items-center gap-1.5">
                  <Layers className="w-4 h-4 text-[#0BCEAF]" />
                  Project Overview
                </h4>
                <p className="text-gray-700 leading-relaxed text-sm sm:text-base">
                  {activeLightbox.projectDescription}
                </p>
              </div>

              {/* Technologies Used */}
              {activeLightbox.technologies && activeLightbox.technologies.length > 0 && (
                <div className="mb-6">
                  <h4 className="text-xs uppercase font-extrabold tracking-wider text-gray-500 mb-2.5 flex items-center gap-1.5">
                    <Code2 className="w-4 h-4 text-[#0BCEAF]" />
                    Technologies Used
                  </h4>
                  <div className="flex flex-wrap gap-2">
                    {activeLightbox.technologies.map((tech, idx) => (
                      <span
                        key={idx}
                        className="px-3 py-1 bg-[#0BCEAF]/10 text-[#089e86] font-semibold text-xs rounded-lg border border-[#0BCEAF]/20"
                      >
                        {tech}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* My Contribution */}
              {activeLightbox.contributions && activeLightbox.contributions.length > 0 && (
                <div className="mb-6">
                  <h4 className="text-xs uppercase font-extrabold tracking-wider text-gray-500 mb-2.5 flex items-center gap-1.5">
                    <CheckCircle2 className="w-4 h-4 text-[#0BCEAF]" />
                    My Contribution
                  </h4>
                  <ul className="space-y-2 text-sm sm:text-base text-gray-700">
                    {activeLightbox.contributions.map((point, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-[#0BCEAF] mt-2 flex-shrink-0" />
                        <span>{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Key Features */}
              {activeLightbox.keyFeatures && activeLightbox.keyFeatures.length > 0 && (
                <div className="mb-6">
                  <h4 className="text-xs uppercase font-extrabold tracking-wider text-gray-500 mb-2.5 flex items-center gap-1.5">
                    <CheckCircle2 className="w-4 h-4 text-[#0BCEAF]" />
                    Key Features
                  </h4>
                  <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-sm sm:text-base text-gray-700">
                    {activeLightbox.keyFeatures.map((feature, idx) => (
                      <li key={idx} className="flex items-start gap-2 bg-gray-50 p-2.5 rounded-lg border border-gray-100">
                        <span className="w-2 h-2 rounded-full bg-[#0BCEAF] mt-1.5 flex-shrink-0" />
                        <span className="font-medium text-xs sm:text-sm">{feature}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Action Buttons */}
              <div className="flex justify-between items-center pt-5 border-t border-gray-100 flex-wrap gap-3">
                <a
                  href="https://github.com/Deepavenkat0410"
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-2 text-sm text-gray-800 font-bold hover:text-[#0BCEAF] transition-colors"
                >
                  <Github className="w-4 h-4" />
                  GitHub Repository
                </a>
                <div className="flex gap-3">
                  <button
                    onClick={() => setActiveLightbox(null)}
                    className="px-6 py-2.5 bg-gray-100 text-gray-700 font-bold text-sm rounded-full hover:bg-gray-200 transition-colors"
                  >
                    Close
                  </button>
                  <a
                    href="#contact"
                    onClick={() => setActiveLightbox(null)}
                    className="px-6 py-2.5 bg-[#0BCEAF] text-white font-bold text-sm rounded-full hover:bg-[#089e86] transition-colors inline-flex items-center gap-2 shadow-md hover:shadow-lg"
                  >
                    Contact Developer
                    <ExternalLink className="w-4 h-4" />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </section>
  );
};

